version: '3'
services:
  vm-build:
    build: './'
    working_dir: /tmp/work/base
    command: "packer build packer_WindowsServer_on_aws.json"
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
